services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: student-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StudentPassword123!
    ports:
      - "1433:1433"
    networks:
      - student-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'StudentPassword123!' -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: student-demo-api
    build:
      context: .
      dockerfile: StudentDemo.API/Dockerfile
    container_name: student-api
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SQL_CONN=Server=db;Database=StudentDemoDb;User Id=sa;Password=StudentPassword123!;Encrypt=False;TrustServerCertificate=True;Connection Timeout=60;
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - student-network
    restart: on-failure

networks:
  student-network:
    driver: bridge
